version: "2.0"
services:
    php_fpm:
        build:
            context: ..
            dockerfile: ./Docker/Dockerfile
            args:
                APP_ENV: dev
        environment:
                PHP_IDE_CONFIG: "serverName=sf.local"
                MYSQL_ROOT_PASSWORD: root
                MYSQL_USER: dev
                MYSQL_PASSWORD: dev
                MYSQL_DATABASE: sf
                MYSQL_HOST: mysql_db
        ports:
                - 3000:3000
                - 8080:80
        volumes:
                - ../src:/var/www/probearbeit:cached
        image: php_fpm
        extra_hosts:
            - "sf.local:127.0.0.1"


    mysql_db:
        container_name: mysql_db
        image: mysql:5.7.21
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: dev
            MYSQL_PASSWORD: dev
            MYSQL_DATABASE: sf
        ports:
            - "3308:3306"
        restart: always
        volumes:
            - ../mysql-data:/var/lib/mysql
            - ../src:/var/www/probearbeit